name: CoreBungee
version: ${project.version}
main: club.catmc.core.bungee.BungeePlugin
author: CatMC
description: Core BungeeCord plugin with ACF commands

permissions:
  core.command:
    description: Allows using core command
    default: true
